version: "3.9"
services:
  db:
    build: ./external/db
    container_name: db-container
    working_dir: /__work/db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
